### PR TITLE
Export to GitHub's internal format

### PR DESCRIPTION
**Pull request by abusalimov**
This PR adds a support for exporting issues into JSON format used by GitHub internally. You may ask their support to import issues from that format to overcome some current limitations:
  - No API rate limit
  - No annoying notifications to watchers
  - Preserve the original timestamps of issues and comments
  - Preserve the authorship, given a mapping between emails and GitHub users for those who authorized a special migrator OAuth2 application

The `exportissues.py` script also has some improvements comparing to the original `migrateissues.py` that are not related to bothering GitHub support, and could be eventually backported to the original script:
  - `config.ini` with defaults for options, overridable from the command line
  - `labels.ini` for better control of how labels/milestones map between GCode and GitHub
  - `commits.map` for mapping between, e.g. SVN and Git commit references
  - `authors.json` for mapping emails to @mentions
  - `messages.txt` for editing issues and comments before exporting
  - Uploading text attachments to Gist
  - Better support for issue updates, like "assigned to" / "added label" / "moved to milestone"
  - Better Markdown formatting of the result

I've made these improvements and used the script among with https://github.com/abusalimov/github-migrator-gae to migrate https://github.com/embox/embox; you migth check the [result](https://github.com/embox/embox/labels/imported) yourself.

I'd like not to disclose the guy from GitHub support who helped me; if you'd ever be interested in moving the issues "the hard way", just [contact](https://github.com/contact) them and they may (or may not, I dunno) decide to help you. Anyway, you'll get some necessary info on the migration, including the format of JSON, in case if you'd like to tweak the result.

Based on the original work of @skirpichev.

### CODE REVIEW

**Comment by skirpichev** [comment]
@abusalimov, thank you for working hard on my dirty scripts, but...

> I'd like not to disclose the guy from GitHub support who helped me; if you'd ever be interested in moving the issues "the hard way", just contact them and they may (or may not, I dunno) decide to help you.

I think, nothing will be wrong, if I quote my question to github support:
> sorry for late (triggered by closing of the googlecode), and, perhaps,
> a stupid question, but...
>
> Shall I return back my solution (i.e. exportissues tool [1]) to the
> https://github.com/arthur-debert/google-code-issues-migrator project?
>
> It's not clear for me whether you want to promote of this feature
> (i.e. the manual imports), but it seems the quality of my imports is better then
> from the "official" googlecode export tool, i.e.:
> https://github.com/EmulatorArchive/bizhawk/issues
> vs
> https://github.com/fredrik-johansson/mpmath/issues?q=is%3Aopen+is%3Aissue+label%3Aimported
>
> [1] on this branch
> https://github.com/skirpichev/google-code-issues-migrator/tree/my2

Their answer:
> We're not currently offering manual imports for the Google Code migration but thanks for offering.

PS: Original script was used for SymPy and mpmath.

**Comment by abusalimov** [comment]
@skirpichev, thank you too! :beers: 

In fact, it was a GitHub support guy who told me about your scripts:

> > And just in case, is there any tools for exporting Google Code issues into
> > the format you described?
>
> I can remember one other user who did this and open-sourced things:
>
> https://github.com/skirpichev/google-code-issues-migrator/branches
>
> I believe he made the changes in the my and my2 branches, but I haven't looked at that code myself so I can't say what it does for sure.

I didn't ask him whether it's OK to link to a page containing a detailed description of the format used (and so I don't do that), but I told him about my intentions to propose my changes as a PR and got positive feedback:

> > ​I'm going to push our code base in a while, and after that I'll publish the remaining fixes (to the migrator) that I've made recently, so that you could suggest it to the next generation of folks moving from Google Code and willing to do it "the hard way". :)
>
> Glad to hear you're happy with the import! And thanks for updating the tools -- I'd be happy to share them if anyone else wants to go through this fun process of importing issues. :)

So I believe there's nothing criminal in making a PR. :)

**Comment by skirpichev** [comment]
> In fact, it was a GitHub support guy who told me about your scripts:

Was it before or after http://google-opensource.blogspot.jp/2015/03/farewell-to-google-code.html
?

> So I believe there's nothing criminal in making a PR. :)

Yes, but if now they don't offer any support for manual migrations - this tool is useless.

**Comment by abusalimov** [comment]
I was told about your scripts before this announcement, as seen from my commits, in December 2014 to be clear, just after I noticed the migration of [golang](https://github.com/golang/go). However, I finished moving our project just recently, and the second quotation is from a conversation two weeks ago.

I have no clue whether they are going to continue offering a manual migration. It's worth asking them in each case individually. I guess they could refuse small project with 1-2 developers and 10-100 issues. Though I believe that they most likely would assist in case the manual migration makes happier more people.

**Comment by abusalimov** [comment]
@arthur-debert ping. Any chances of this getting some attention / being merged or refused?

**Comment by joelpt** [comment]
This is great work. However I'm going to reject this pull request for the following reasons:

1. The inclusion of exportissues.py and its supplementary files (which migrateissues.py doesn't understand), in the same folder as migrateissues.py, is likely to confuse users.
2. For the new functions you have added to migrateissues.py, we should have at least a 1 line comment with each explaining what they do. For example it's not clear what "dereference" does without reading a good chunk of code.

Regarding #1, would it make more sense to have exportissues be its own dedicated project on github? We could add a link to it in this repo's README.md so that people can easily discover this specialized tool.

Regarding #2, can you submit an updated pull request just for migrateissues.py that includes your changes, along with comments for the new functions?

**Pull request closed without merging**
